# Generated by Django 4.2.30 on 2026-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RolloutState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("ROLLING_OUT", "Rolling Out"),
                            ("COMPLETE", "Complete"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("v1_model_type", models.CharField(max_length=50)),
                (
                    "v2_model_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("v1_weight", models.IntegerField(default=100)),
                ("v2_weight", models.IntegerField(default=0)),
                ("request_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("step_size", models.IntegerField(default=10)),
                ("interval_sec", models.IntegerField(default=5)),
                ("error_threshold", models.FloatField(default=0.2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
