# Generated by Django 4.2.30 on 2026-09-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolloutState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ROLLING_OUT', 'Rolling Out'), ('COMPLETE', 'Complete'), ('ROLLED_BACK', 'Rolled Back')], default='IDLE', max_length=20)),
                ('active_model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('active_mlflow_version', models.CharField(blank=True, max_length=20, null=True)),
                ('canary_model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('canary_mlflow_version', models.CharField(blank=True, max_length=20, null=True)),
                ('active_weight', models.IntegerField(default=100)),
                ('canary_weight', models.IntegerField(default=0)),
                ('active_request_count', models.IntegerField(default=0)),
                ('active_error_count', models.IntegerField(default=0)),
                ('canary_request_count', models.IntegerField(default=0)),
                ('canary_error_count', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('step_size', models.IntegerField(default=10)),
                ('interval_sec', models.IntegerField(default=5)),
                ('error_threshold', models.FloatField(default=0.2)),
                ('rollback_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registered_model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('exact_mlflow_version', models.CharField(blank=True, max_length=20, null=True)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('prediction_result', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('rollout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='model_management.rolloutstate')),
            ],
        ),
    ]
