# Generated by Django 4.2.30 on 2026-09-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionlog',
            options={'ordering': ['request_number']},
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='is_canary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='request_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rolloutstate',
            name='triggering_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_rollback', to='model_management.predictionlog'),
        ),
    ]
