# Generated by Django 5.2.17 on 2026-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REGISTERED', 'Registered'), ('FAILED_LOADING', 'Failed Loading'), ('FAILED_MLFLOW', 'Failed MLflow')], default='PENDING', max_length=50),
        ),
    ]
